### ISSUE TITLE
Serious dupe of everything

### ISSUE THREAD

**Issue by Wise1986** [TheCricket/Chisel-2#257]
Chisel 2.3.7 allows to dupe any block:

Steps to reproduce:
[REDACTED]

**Comment by CptSpaceToaster** [comment]
Related to: https://github.com/TheCricket/Chisel-2/issues/236

**Comment by tterrag1098** [comment]
This does not work for me. I reproduced exactly your steps and it does not dupe the blocks.

**Comment by tterrag1098** [comment]
I've added some code to prevent this being able to happen and censored your post in case it is possible in some situation I can't reproduce.

**Comment by Wise1986** [comment]
look this video to see the process in details. Found this today and then checked on my pack and reproduced this dupe:

https://www.youtube.com/watch?v=1DOx8GU2uW0&t=51

**Comment by TheCricket** [comment]
We censored it for a reason. Never make a video of a dupe public

**Comment by Wise1986** [comment]
its not mine, just found it on youtube

**Comment by tterrag1098** [comment]
Regardless don't publicize it. This is fixed now.

**Comment by Wise1986** [comment]
i have compiled latest dev version and this bug is still reproducible

**Comment by frozenLake** [comment]
Erm, might need to censor your post too, @TheCricket, as it has the link.

**Comment by Drullkus** [comment]
@frozenLake Done

**Comment by Wise1986** [comment]
its not a way out you have to release fixed version asap, current fix doesnt work

**Comment by tterrag1098** [comment]
@Wise1986 We will release the new version when it is ready and no sooner.
